### ISSUE TITLE
[Suggestion] fileed.php/filereceive.php - New way to display error message? 

### ISSUE THREAD

**Issue by a17andby** [HGustavs/LenaSYS#6590]
Current error message:
![Screenshot from 2019-05-03 13-13-25](https://user-images.githubusercontent.com/49235724/57134133-6b601080-6da5-11e9-80fd-ecaf514d67a0.png)

Maybe we can create a much better way to display error messages?

**Comment by HGustavs** [comment]
Yes not a bad idea.

Can someone make a mock-up.

I want it to be able to handle a wide variet of error conditions, permission denied, extension problems, mime type problems etc.

An if more than one file is affected.

**Comment by a17alian** [comment]
From what I understand the error messages only uses echo typ write a message on the filereceive.php page,  #6744 and this issue. The filereceive.php should at least redirect the user back to  fileed.php. Maybe using the header function or another type of redirect.

**Comment by a17adasy** [comment]
To next years students:
When assigned to this issue my thinking was not to change the structure too much. But I found out that when you upload a file you are redirected to a new page where you either get redirected back if the file was accepted or stay on that page with a pretty useless array printed out and a text below that saying what the problem was. Firstly to get better error message the array can basically just not get printed and have another array that gets filled with what didnt work. To get this printed on the page where you tried to upload the file (fileed), which is probably what you want. You need to send the array with a get request or store it in session. I did a quick test with storing it in session which can be seen in the branch: 
https://github.com/HGustavs/LenaSYS/tree/GruppB2019W22%236590. This is probably not the ideal way either since the user will get first redirected to the filereceive.php page and then back to the fileed page automatically. Maybe a better way is handling the error on the same page. A structure change may then be needed. Perhaps manage errors in fileedservice.php instead. Hopefully something of this is useful.

**Comment by a18jimol** [comment]
When I try to test this issue there are a couple of problems i encounter.
First, I don't get the actual array you are talking about so I wonder if it has been fixed in some other issue or if it's some other bug. When I test the a17adasy branch I get the array as you say.

Then we encounter the problem that you can only upload files in certain places, you go to an example in a course and want to see files then it can upload but if you are in a course and want to change files then you cannot upload. 

And another problem is that some files that should be allowed are not allowed like PNG.

@HGustavs Should we make new issues for this or try to continue on this one?

**Comment by a97marbr** [comment]
not being able to upload a PNG I would say is a separate issue.

**Comment by a18jonsj** [comment]
We encountered 2 new issues while working on this issue. Issue #7905 and issue #7858. We still can not get to the array that is mentioned in this issue tho and if try to upload a type of file that is not allowed as discussed in issue #7905, i get directed to the same url that you can see in the screenshot of this issue, but instead of an array showing it says "Extension "X" not allowed" so in a way it seems like this issue has been solved.

**Comment by a18jimol** [comment]
In this issue we still don't find the array the issue is about but in @HGustavs comment you say you want it to handle different types of errors. I wonder how we can solve that, do you want it in a similar way as issue #6744 that the error message is in fileed.php instead of filerecive.php. Or do you want the error message to be on filereceive.php and we fix it there to give better explanation to the error?

**Comment by a18jonsj** [comment]
We changed it so now you get redirected back to fileed.php and the errormessage is shown with some styling after trying to upload a file that is not allowed. 
Example: 
![image](https://user-images.githubusercontent.com/49142617/79336462-140a7000-7f24-11ea-9ba3-cd74c0852cdd.png)

Is this the way you want the errormeassages to be shown?

**Comment by a18jonsj** [comment]
The application is now able to handle and display errormessages in a better way, if the user is trying to upload a file with an extension thats is not allowed, access a course the user doesnt have the rights to, or if there is a problem uploading a file. 

Now when an error accurs you get redirected to fileed.php and the error message is displayed as shown in the previously posted image, with a text describing what went wrong.
